aws/aws-encryption-sdk-cli

setup.py

adding description field to setup.py

adding description field to setup.py

---

src/aws_encryption_sdk_cli/internal/metadata.py
test/integration/test_i_aws_encryption_sdk_cli.py
test/unit/test_aws_encryption_sdk_cli.py
test/unit/test_io_handling.py

skip symlink tests on Windows #128

 skip symlink tests on Windows

---

.travis.yml
README.rst

updating Travis CI config to use new testenv targets #92

updating Travis CI config to use new testenv targets

---

README.rst

I mis-guessed what the url for the AppVeyor badge would be :(

fixing AppVeyor badge urls

---

.github/PULL_REQUEST_TEMPLATE.md
.gitignore
CODE_OF_CONDUCT.md
CONTRIBUTING.md
NOTICE
test/integration/integration_test_utils.py

Adding the stock AWS contributing/code of conduct files.

Adding contributing docs

---

CHANGELOG.rst
CONTRIBUTING.md
README.rst
src/aws_encryption_sdk_cli/internal/identifiers.py

*Issue #, if available:* n/a
*Description of changes:* Documentation changes to update hyperlinks, and minor version bump.
Please note reuse of already in-flight version 1.1.5, since this is the bundle of changes that will go out together to PyPI etc.

Move repository from awslabs to aws.

---

CHANGELOG.rst
src/aws_encryption_sdk_cli/internal/identifiers.py

Bump version to 1.1.7 and update changelog in preparation for release.

bump to 1.1.7 and update changelog

---

README.rst

chore: Add security issue notification to readme

---

CHANGELOG.rst
README.rst
requirements.txt
src/aws_encryption_sdk_cli/__init__.py
src/aws_encryption_sdk_cli/internal/arg_parsing.py
src/aws_encryption_sdk_cli/internal/identifiers.py
src/aws_encryption_sdk_cli/internal/io_handling.py
src/aws_encryption_sdk_cli/internal/master_key_parsing.py
src/aws_encryption_sdk_cli/internal/metadata.py
src/aws_encryption_sdk_cli/internal/mypy_types.py
src/aws_encryption_sdk_cli/key_providers.py
test/unit/internal/test_arg_parsing.py
test/unit/internal/test_io_handling.py
test/unit/internal/test_master_key_parsing.py
test/unit/internal/test_metadata.py
test/unit/test_aws_encryption_sdk_cli.py
test/unit/test_key_providers.py
tox.ini

Updates to the AWS Encryption SDK.

Release 1.7.0

---

CHANGELOG.rst
README.rst
requirements.txt
src/aws_encryption_sdk_cli/__init__.py
src/aws_encryption_sdk_cli/internal/arg_parsing.py
src/aws_encryption_sdk_cli/internal/identifiers.py
src/aws_encryption_sdk_cli/internal/io_handling.py
src/aws_encryption_sdk_cli/internal/mypy_types.py
test/integration/integration_test_utils.py
test/unit/internal/test_arg_parsing.py
test/unit/internal/test_io_handling.py
test/unit/internal/test_metadata.py
test/unit/test_aws_encryption_sdk_cli.py

Updates to the AWS Encryption SDK.

Release 2.0.0

---

src/aws_encryption_sdk_cli/internal/mypy_types.py
test/unit/internal/test_arg_parsing.py
tox.ini

This aims to fix the unit tests in the CI/CD pipeline to unblock other changes.

fix: CI/CD

---

src/aws_encryption_sdk_cli/__init__.py
src/aws_encryption_sdk_cli/internal/arg_parsing.py
test/unit/test_aws_encryption_sdk_cli.py

*Description of changes:* Pylint fix to get CI green

chore: Fix pylint C0103(invalid-name)

---

api_compatibility_tests/compatibility-requirements/1.9.0
api_compatibility_tests/compatibility-requirements/2.2.0
api_compatibility_tests/tox.ini
codebuild/release/prod-release.yml
codebuild/release/test-release.yml
codebuild/release/validate.yml

Applying the same structure as we already have in the https://github.com/aws/aws-encrytion-sdk-python repo.

chore: Release using codebuild

---

CHANGELOG.rst
README.rst
api_compatibility_tests/compatibility-requirements/1.9.0
api_compatibility_tests/compatibility-requirements/2.2.0
api_compatibility_tests/tox.ini
codebuild/release/prod-release.yml
codebuild/release/test-release.yml
codebuild/release/validate.yml
requirements.txt
src/aws_encryption_sdk_cli/__init__.py
src/aws_encryption_sdk_cli/internal/arg_parsing.py
src/aws_encryption_sdk_cli/internal/identifiers.py
src/aws_encryption_sdk_cli/internal/io_handling.py
test/integration/integration_test_utils.py
test/integration/test_i_aws_encryption_sdk_cli.py
test/unit/internal/test_arg_parsing.py
test/unit/internal/test_io_handling.py
test/unit/internal/test_logging_utils.py
test/unit/internal/test_master_key_parsing.py
test/unit/test_aws_encryption_sdk_cli.py
test/unit/test_key_providers.py

See https://github.com/aws/aws-encryption-sdk-cli/security/advisories/GHSA-89v2-g37m-g3ff

feat: Improvements to the message decryption process

---

README.rst

*Issue #, if available:* Wrong required version in README
*Description of changes:* Required ESKD version is 2.3.0

fix: required version in README

---

README.rst
SUPPORT_POLICY.rst

As with ESDK, current statuses and dates are forward looking, based on our plan to deprecate python 2 support for this library.

chore: Add support policy

---

CHANGELOG.rst
README.rst
src/aws_encryption_sdk_cli/internal/identifiers.py

Text mostly copied from the same changes in the Python ESDK.

chore: Prep for release 3.1.0

---

src/pylintrc
test/pylintrc

chore: Fix CI

---

.github/workflows/ci_static-analysis.yaml
.github/workflows/ci_tests.yaml
codebuild/py35/examples.yml
codebuild/py35/integ.yml
codebuild/py36/examples.yml
codebuild/py36/integ.yml
codebuild/py37/examples.yml
codebuild/py37/integ.yml
codebuild/py38/examples.yml
codebuild/py38/integ.yml
codebuild/py39/examples.yml
codebuild/py39/integ.yml

*Issue #, if available:* Update Minor Python versions used for testing.
- In CodeBuild, use the latest release of Python Minor versions as of 2021-11-08
- In GitHub, use the latest version of `actions/setup-python`

ci: Update CI

---

buildspec.yml
codebuild/py310/examples.yml
codebuild/py310/integ.yml
tox.ini

ci(py310): test against Python 3.10.0

---

src/aws_encryption_sdk_cli/__init__.py
src/aws_encryption_sdk_cli/compatability.py
test/pylintrc
test/unit/test_compatability.py

*Issue #, if available:* Check Python Runtime
*Description of changes:* Implements A runtime check on the Python Version.
Runtime Check:
- Issues a WARNING if the Python Version will become/is unsupported.
- Will start issuing WARNING for Python Version less than 3.6.

feat(compatability): Check Python Runtime

---

.github/workflows/ci_static-analysis.yaml
.github/workflows/ci_tests.yaml
codebuild/python_38.yml
src/aws_encryption_sdk_cli/internal/metadata.py
src/pylintrc
test/pylintrc
test/unit/internal/test_metadata.py
tox.ini

Fix some minor pylint issues.
mypy was pulling up a bunch of errors, so I'm pinning to the version of mypy we were using when we wrote these checks. This branch is in maintenance mode, so I'm not going to prioritize getting mypy into a perfect state.

chore: fix broken static analysis

---

.github/CODEOWNERS

chore: Add CODEOWNERS file (3.x)

---

src/aws_encryption_sdk_cli/internal/identifiers.py

*Issue #, if available:* Bump Version to 4.1.0
*Description of changes:* Bump Version to 4.1.0

chore(identifiers): bump version to 4.1.0

---

api_compatibility_tests/compatibility-requirements/4.1.0
api_compatibility_tests/tox.ini

*Issue #, if available:* ci(api_compatibility): add version 4.1.0
*Description of changes:* ci(api_compatibility): add version 4.1.0

ci(api_compatibility): add version 4.1.0

---

dev_requirements/linter-requirements.txt

chore(deps): bump black from 22.1.0 to 22.3.0

---

dev_requirements/linter-requirements.txt
doc/conf.py
requirements.txt
test/integration/test_i_aws_encryption_sdk_cli.py

Update 1.x esdk minor version, update linter-deps, and run formatter

chore: update esdk to new 1.x minor version

---

dev_requirements/linter-requirements.txt
doc/conf.py
requirements.txt
test/integration/test_i_aws_encryption_sdk_cli.py

Update 2.x esdk minor version, update linter-deps, and run formatter

chore: update esdk to new 2.x minor version

---

CHANGELOG.rst
README.rst
api_compatibility_tests/compatibility-requirements/1.9.1
api_compatibility_tests/compatibility-requirements/2.2.1
api_compatibility_tests/compatibility-requirements/3.1.1
api_compatibility_tests/tox.ini
src/aws_encryption_sdk_cli/internal/identifiers.py

chore: Prepare for release

---

api_compatibility_tests/tox.ini

fix: Fix api compatibility 3.1.1 target

---

api_compatibility_tests/tox.ini

fix: Fix api compatibility 2.2.1 target

---

api_compatibility_tests/tox.ini

fix: Fix api compatibility 1.9.1 target

---

SUPPORT_POLICY.rst

*Issue #, if available:* Mark 1.x, 2.x, & 3.x End-of-Support
- Update Support Policy, marking 1.x, 2.x, & 3.x End-of-Support

docs(SupportPolicy): Mark 1.x, 2.x, & 3.x End-of-Support

---

codebuild/release/validate.yml

fix(CodeBuild): api testing needs pyenv 3.8

---

.github/workflows/ci_static-analysis.yaml
.github/workflows/ci_tests.yaml
.github/workflows/install.yaml
.github/workflows/repo-sync.yml
dev_requirements/ci-requirements.txt
dev_requirements/linter-requirements.txt
dev_requirements/test-requirements.txt
tox.ini

chore: bump deps

---

.github/workflows/ci_tests.yaml
.readthedocs.yaml

fix(docs; gha): updated .readthedocs.yaml; macos-latest to macos-12
