CHANGELOG.rst, README.rst, setup.py, src/aws_encryption_sdk_cli/__init__.py, src/aws_encryption_sdk_cli/internal/arg_parsing.py, src/aws_encryption_sdk_cli/internal/encoding.py, src/aws_encryption_sdk_cli/internal/identifiers.py, src/aws_encryption_sdk_cli/internal/io_handling.py, src/aws_encryption_sdk_cli/internal/logging_utils.py, src/aws_encryption_sdk_cli/internal/master_key_parsing.py, src/aws_encryption_sdk_cli/internal/metadata.py, src/aws_encryption_sdk_cli/internal/mypy_types.py, src/aws_encryption_sdk_cli/key_providers.py
fix for Python 3.5.0/3.5.1 compatibility issue #114 
Tested with Python:
* 2.7.13
* 3.4.6
* 3.5.0
* 3.5.1
* 3.5.2
* 3.5.3
* 3.6.2
=> fix for Python 3.5.0/3.5.1 compatibility issue

CHANGELOG.rst, setup.py, src/aws_encryption_sdk_cli/internal/identifiers.py
See also https://github.com/awslabs/aws-encryption-sdk-cli/issues/122
Testing:
- Reproduced permissions error using sdist install (`setup.py sdist` + `pip install aws-encryption-sdk-cli*.tar.gz`)
- Resolved permissions error with this patch applied using sdist install
- Double checked `MANIFEST.in` and verified output .tar.gz still includes metadata files (`README.rst`, `CHANGELOG.rst`, `LICENSE`, `requirements.txt`)
- Builds / unit tests pass
Assigning @mattsb42-aws as reviewer -- it's possible there's something I've missed here such that this isn't the right fix, but I think this might do it and I wanted to get a PR out ASAP to help prevent people from being blocked on install.
=> Fix permissions issue on install, and update revision version number.

src/aws_encryption_sdk_cli/__init__.py, src/aws_encryption_sdk_cli/internal/arg_parsing.py, src/aws_encryption_sdk_cli/internal/encoding.py, src/aws_encryption_sdk_cli/internal/identifiers.py, src/aws_encryption_sdk_cli/internal/io_handling.py, src/aws_encryption_sdk_cli/internal/logging_utils.py, src/aws_encryption_sdk_cli/internal/master_key_parsing.py, src/aws_encryption_sdk_cli/internal/metadata.py, src/aws_encryption_sdk_cli/key_providers.py, test/unit/test_encoding.py, tox.ini
* Blacklisting pytest 3.3.0 (#125) and adding tests to make sure we catch it if pytest breaks in this way again. https://github.com/pytest-dev/pytest/issues/2957
* Fixing some minor formatting issues I missed in #118
=> minor cleanup and blacklisting pytest 3.3.0

src/aws_encryption_sdk_cli/internal/io_handling.py, test/integration/test_i_aws_encryption_sdk_cli.py, test/unit/test_io_handling.py
expanding input and output file paths to abspath and adding corresponding tests https://github.com/awslabs/aws-encryption-sdk-cli/issues/120
=> expanding input and output file paths to abspath and adding corresponding tests

src/aws_encryption_sdk_cli/internal/metadata.py, test/unit/test_metadata.py
moving metadata writer to binary mode when writing to files https://github.com/awslabs/aws-encryption-sdk-cli/issues/121
=> moving metadata writer to binary mode when writing to files

src/aws_encryption_sdk_cli/__init__.py, src/aws_encryption_sdk_cli/internal/arg_parsing.py, src/aws_encryption_sdk_cli/internal/encoding.py, src/aws_encryption_sdk_cli/internal/identifiers.py, src/aws_encryption_sdk_cli/internal/io_handling.py, src/aws_encryption_sdk_cli/internal/logging_utils.py, src/aws_encryption_sdk_cli/internal/master_key_parsing.py, src/aws_encryption_sdk_cli/internal/metadata.py, src/aws_encryption_sdk_cli/internal/mypy_types.py, src/aws_encryption_sdk_cli/key_providers.py, test/integration/README.rst, test/integration/integration_test_utils.py, test/integration/test_i_aws_encryption_sdk_cli.py, test/integration/test_i_key_providers.py, test/integration/test_i_logging_utils.py, test/unit/test_aws_encryption_sdk_cli.py, test/unit/test_io_handling.py, test/unit/unit_test_utils.py, tox.ini
* moving integration tests off of config file and onto environment variables #62 
* consolidating some common helper functions across unit and integration tests into helper modules
* whitelisting the `except` blocks after `typing` imports to exclude them from coverage miss reports
* I must have missed this when we originally did it, but these are code paths that we expect never to run on most platforms, and without this whitelisting they clutter up the coverage reports and mask actual coverage misses that we need to be aware of.
=> moving integration tests off of config file and onto environment variables

setup.cfg, test/integration/README.rst, test/integration/integration_test_utils.py, test/integration/test_i_aws_encryption_sdk_cli.py, test/integration/test_i_key_providers.py, test/integration/test_i_logging_utils.py, test/unit/test_arg_parsing.py, test/unit/test_aws_encryption_sdk_cli.py, test/unit/test_encoding.py, test/unit/test_io_handling.py, test/unit/test_key_providers.py, test/unit/test_logging_utils.py, test/unit/test_master_key_parsing.py, test/unit/test_metadata.py, tox.ini
* consolidating common 
* cleaning up integration test handling #67
* marking all tests/modules as unit, functional, local (no network access required), and/or integration (network access required)
* changing test handling to run local/integ tests as separate tox testenvs rather than skipping integration tests if a specific environment variable is not found : this makes it much clearer if integration tests fail, distinct from local tests)
* adding flake8-print #22
* adding more useful error output if KMS key id environment variable is not set
* adding requirement that KMS key id environment variable is an CMK ARN (required for logging tests without also requiring DescribeKey access)
=> maintenance updates to simplify test framework

test/unit/test_aws_encryption_sdk_cli.py
Addresses #139 
I don't think this necessarily merits a version bump or additional release since it only affects the tests.
=> reworking build_same_files_and_dirs helper to explicitly cover all return cases

README.rst, appveyor.yml, test/integration/integration_test_utils.py, test/integration/test_i_aws_encryption_sdk_cli.py, test/integration/test_i_key_providers.py, test/unit/test_arg_parsing.py
Adding AppVeyor CI integration #91. Also required some fixes to make integration tests run properly on Windows.
We don't have AppVeyor granted access to awslabs yet, but here's the latest run from my branch: https://ci.appveyor.com/project/mattsb42-aws/aws-encryption-sdk-cli/build/1.0.15
=> Adding AppVeyor CI integration

CHANGELOG.rst, README.rst, src/aws_encryption_sdk_cli/internal/arg_parsing.py, src/aws_encryption_sdk_cli/internal/identifiers.py, test/unit/test_arg_parsing.py, tox.ini
Fixes #110 as well as in the process adding support for escaping single quotes in Linux and MacOS and escaping characters in Windows using the Windows-expected "`" character.
Also bumps the version to 1.1.4
https://travis-ci.org/mattsb42-aws/aws-encryption-sdk-cli/builds/327895074
https://ci.appveyor.com/project/mattsb42-aws/aws-encryption-sdk-cli/build/1.0.23
=> fix for Windows config file quote character handling

tox.ini
`pytest` `3.4.0` introduced a breaking change that broke `pytest-sugar`. A fix is pending for that now, but turning it off for now a) because the PR is not merged and I don't want to block on their release cycle, and b) because most of why I added `pytest-sugar` in the first place (rolling % completion of test suite) was added into `pytest` itself in `3.3.0`.
Also did a bit of minor cleanup of the test requirements: `coverage` will always be pulled in by `pytest-cov`, so no need to specify that directly, and updating the `pytest` version requirement to be consistent with https://github.com/awslabs/aws-encryption-sdk-python .
=> removing pytest-sugar pending https://github.com/Frozenball/pytest-sugar/pull/133

tox.ini
*Issue #, if available:* #147 
* Single-source mypy basepython and dependencies
* Blacklist mypy 0.570 and 0.580
* Add passthrough for testing environment variable
=> blacklist mypy 0.570 and 0.580

.travis.yml, README.rst, appveyor.yml, setup.py, tox.ini
*Issue #, if available:* #151 
CPython 3.0 was released last month. We should start testing it.
I also realized after merging #150 that I forgot to point the pyversions badge at the correct repo..so this fixes that too.
=> add CPython 3.7 to tox envlist and CI configs

requirements.txt, setup.py, test/unit/internal/test_arg_parsing.py
*No public issue*
Update to only check for Python's typing module if and only if we're running Python before 3.5.0
=> Check for typing only in Python < 3.5

CHANGELOG.rst, src/aws_encryption_sdk_cli/internal/identifiers.py
Moving version from 1.1.5 to 1.1.6 -- Update requirements to only require the typing module for Python versions earlier than 3.5
=> MV bump from 1.1.5 to 1.1.6; update Changelog

requirements.txt, src/aws_encryption_sdk_cli/internal/arg_parsing.py, src/aws_encryption_sdk_cli/internal/io_handling.py, src/aws_encryption_sdk_cli/internal/logging_utils.py
This removes our install dependency on typing and adds shims on failed imports where necessary.
fixes #166 
I was unable to duplicate the reported issue that triggered #166, but after considering how we are actually using `typing` (ie: only for typehints), I think that the right answer is to remove our install dependency entirely.
We only need `typing` to actually exist and work correctly when we do our type analysis, and we always run that with a version newer than 3.5.2, and the shims let the code work as intended when `typing` is not present.
=> remove install dependency on typing

tox.ini
Resolves compatibility issue between coverage 5 and the mypy coverage report.
This unblocks our Travis CI checks.
=> chore: set coverage version to support mypy coverage file workaround

CHANGELOG.rst, README.rst, requirements.txt, src/aws_encryption_sdk_cli/__init__.py, src/aws_encryption_sdk_cli/internal/arg_parsing.py, src/aws_encryption_sdk_cli/internal/identifiers.py, src/aws_encryption_sdk_cli/internal/master_key_parsing.py, src/aws_encryption_sdk_cli/internal/mypy_types.py, src/aws_encryption_sdk_cli/key_providers.py, test/integration/test_i_aws_encryption_sdk_cli.py, test/unit/internal/test_arg_parsing.py, test/unit/internal/test_master_key_parsing.py, test/unit/test_key_providers.py, tox.ini
This change includes fixes for enabling or disabling discovery mode in the CLI.
BREAKING CHANGE: --discovery parameter is removed. It is replaced by a ‘discovery’ attribute of --wrapping-keys parameter. Decrypt commands will fail if ‘discovery’ is used as a parameter. ‘discovery’ attribute is valid only in decrypt
commands where the provider is ‘aws-kms’. The command will fail if ‘discovery’ attribute is combined with any other provider.
See: https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/crypto-cli.html
=> Fixes for enabling or disabling discovery mode in the CLI (1.x)

CHANGELOG.rst, README.rst, requirements.txt, src/aws_encryption_sdk_cli/__init__.py, src/aws_encryption_sdk_cli/internal/arg_parsing.py, src/aws_encryption_sdk_cli/internal/identifiers.py, src/aws_encryption_sdk_cli/internal/master_key_parsing.py, src/aws_encryption_sdk_cli/key_providers.py, test/integration/integration_test_utils.py, test/integration/test_i_aws_encryption_sdk_cli.py, test/unit/internal/test_arg_parsing.py, test/unit/internal/test_master_key_parsing.py, test/unit/test_aws_encryption_sdk_cli.py, test/unit/test_key_providers.py
This change includes fixes for enabling or disabling discovery mode in the CLI.
BREAKING CHANGE: --discovery parameter is removed. It is replaced by a ‘discovery’ attribute of --wrapping-keys parameter. Decrypt commands will fail if ‘discovery’ is used as a parameter. ‘discovery’ attribute is valid only in decrypt
commands where the provider is ‘aws-kms’. The command will fail if ‘discovery’ attribute is combined with any other provider.
See: https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/crypto-cli.html
=> Fixes for enabling or disabling discovery mode in the CLI (2.x)

.gitignore, buildspec.yml, codebuild/python_27.yml, codebuild/python_35.yml, codebuild/python_36.yml, codebuild/python_37.yml, codebuild/python_38.yml, tox.ini
Adding buildspec to batch build
multiple Python runtimes
* Python 2.7
* Python 3.5
* Python 3.6
* Python 3.7
* Python 3.8
=> chore: Add AWS CodeBuild buildspec

buildspec.yml, codebuild/coverage.yml, setup.cfg, tox.ini
Remove code coverage from default python commands, add a dedicated code coverage environment, as well as code build specs to run it.
See also https://github.com/aws/aws-encryption-sdk-python/pull/325, https://github.com/aws/aws-dynamodb-encryption-python/pull/153
Differences from the other PRs:
* CLI's code coverage isn't as good, so I have to set the threshold a fair bit lower
* Because of above, I'm including both integ and unit tests in the coverage check
*Testing:*
Confirmed build fails if I try to set the coverage threshold higher.
=> chore: Add dedicated code coverage tox environment

src/aws_encryption_sdk_cli/internal/io_handling.py, src/aws_encryption_sdk_cli/internal/metadata.py, test/integration/test_i_aws_encryption_sdk_cli.py
Hits in source code were both false positives (since both were non-trivial control flow and already handling closing the resources).
Hits in test code were reasonable to refactor to use `with`, but `Popen` only supports use as a resource as of Python 3.4, so we'll have to wait on that for now.
=> fix: New pytest warning “consider-using-with”

api_compatibility_tests/compatibility-requirements/1.9.0, api_compatibility_tests/compatibility-requirements/2.2.0, api_compatibility_tests/tox.ini, codebuild/release/prod-release.yml, codebuild/release/test-release.yml, codebuild/release/validate.yml
Applying the same structure as we already have in the https://github.com/aws/aws-encrytion-sdk-python repo.
(cherry picked from commit 11d4c9d9032aca631ebe9655bc1da65cdf5db11a)
*Description of changes:* Back-port #206 to 1.x branch.
Local General Testing:
```
for MINOR_VERSION in 2.7 3.5 3.6 3.7 3.8 ;do
pyenv local $(pyenv versions | grep "^  ${MINOR_VERSION}" | tail -1);
PY_TOX=$(echo $MINOR_VERSION | sed 's/\.//');
PIP_CONFIG_FILE=./private-pypi.config tox -re py$PY_TOX-integ,py$PY_TOX-local -p 2;
done
---
✔ OK py27-local in 14.392 seconds
✔ OK py27-integ in 1 minute, 5.111 seconds
✔ OK py35-local in 13.474 seconds
✔ OK py35-integ in 50.822 seconds
✔ OK py36-local in 13.657 seconds
✔ OK py36-integ in 49.361 seconds
✔ OK py37-local in 12.59 seconds
✔ OK py37-integ in 47.491 seconds
✔ OK …
```
=> chore: Release using codebuild

tox.ini
This matches what we're doing in Python, which is successfully releasing to both Test and Prod: https://github.com/aws/aws-encryption-sdk-python/blob/master/tox.ini#L383-L401
=> chore: Fix test release tox target

api_compatibility_tests/test/integration/test_api_compatibility.py
The compatibility tests did not include the most recent version.
=> chore: update compatibility test to include 3.0

codebuild/release/validate.yml, doc/conf.py, setup.py, src/aws_encryption_sdk_cli/__init__.py, src/aws_encryption_sdk_cli/internal/io_handling.py
Same as we just did for Python ESDK https://github.com/aws/aws-encryption-sdk-python/pull/344
=> chore: Make release validation robust to transient failures

src/aws_encryption_sdk_cli/__init__.py
Emit a deprecation warning to be more vocal about upcoming removal of support.
*Testing:*
The py27 test targets now emit this warning:
```
__init__.py:55: DeprecationWarning: Python 2 support will be removed in a future release. Please upgrade to Python 3.5 or higher.
DeprecationWarning,
```
=> chore: Emit deprecation warning for Py2

test/unit/internal/test_arg_parsing.py, test/unit/internal/test_io_handling.py, test/unit/internal/test_logging_utils.py, test/unit/internal/test_master_key_parsing.py, test/unit/test_key_providers.py
Similar to https://github.com/aws/aws-encryption-sdk-python/pull/351
=> chore: Fix deprecation warnings from pytest

README.rst, src/aws_encryption_sdk_cli/internal/arg_parsing.py
Address issues called out in https://github.com/aws/aws-encryption-sdk-cli/issues/227
*Testing:*
Help string now correct:
```
--commitment-policy {forbid-encrypt-allow-decrypt,require-encrypt-allow-decrypt,require-encrypt-require-decrypt}
Specifies the commitment policy for key commitment.
ex: --commitment-policy=forbid-encrypt-allow-decrypt
```
=> chore: Fixes for commitment policy documentation

.readthedocs.yaml, doc/requirements.txt
Same fixes as here: https://github.com/aws/aws-encryption-sdk-python/commit/193dfc70c44b80e28c9f5abe2000db6084f83ccf
Except this repo didn't yet have a dedicated readthedocs config, so I've added it.
See failing build here: https://readthedocs.org/projects/aws-encryption-sdk-cli/builds/15229926/
=> chore: Fix readthedocs builds

tox.ini
*Issue #, if available:* ci(tox park): unpin python3 version
I have audited the three tox files I could find for any basepython that is not Python3. I only found park.
=> ci(tox park): unpin python3 version

doc/conf.py
Turns out when we moved to a newer version of sphinx (https://github.com/aws/aws-encryption-sdk-cli/pull/245) it changed how we need to specify config options.
See also: https://github.com/aws/aws-encryption-sdk-python/pull/383 and https://github.com/aws/aws-dynamodb-encryption-python/pull/191
*Testing:*
`tox -e serve-docs` shows me the full API docs.
=> chore: fix generated docs

codebuild/release/prod-release.yml, codebuild/release/test-release.yml, requirements.txt, tox.ini
The `tox park` environment was pinned to 3.8 instead of 3. This was causing builds to fail since `latest` in CodeBuild is now 3.9
=> Pin tox park to python3 instead of python3.8

codebuild/release/prod-release.yml, codebuild/release/test-release.yml, requirements.txt, tox.ini
* fix: Pin tox park to python3 instead of python3.8 (#304)
* fix: FOUND_VERSION regex working with mypy type annotation in comment
* fix: Add upper bound to attrs version: Starting with 22.1.0, attrs drops support for Python 2
=> fix: CodeBuild release script errors

dev_requirements/coverage-requirements.txt, dev_requirements/linter-requirements.txt, tox.ini
*Issue #, if available:* Fixes https://github.com/aws/aws-encryption-sdk-cli/actions/runs/2778718751
Fix failing static analysis check by:
1. Upgrading mypy, which now recognizes that `attr` annotated classes are sub-classes of `AttrsInstance`
2. Adding `types-setuptools` and `types-six` to `coverage-requirements.txt`,
which addresses issues raised by the updated `mypy`.
Additional changes to facilitate better static checking:
- Remove `mypy` from `linter-requirements` as it is only invoked when `coverage-requirements` is also loaded. This consolidates `mypy`'s pin to one file.
- Use `mypy`'s `--show-error-codes`, which will report what the typing error violated is.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> ci(mypy-py3): fix mypy-py3 static check

codebuild/release/prod-release.yml, codebuild/release/test-release.yml
Remove using username and password as creds to pypi and use an api token that only restricts to uploading packages.
=> chore(release): add api token to staging and prod release process

CHANGELOG.rst, SUPPORT_POLICY.rst, api_compatibility_tests/tox.ini, codebuild/release/prod-release.yml, codebuild/release/test-release.yml, requirements.txt, src/aws_encryption_sdk_cli/internal/identifiers.py
*Issue #, if available:* Mark 1.x End-of-Support
- Update Changelog for release 1.9.2
- bump version for 1.9.2
- Pin AWS Encryption SDK for Python to at least version 1.10.1
- Add Support Policy
=> chore: 1.x End-of-Support

CHANGELOG.rst, SUPPORT_POLICY.rst, api_compatibility_tests/tox.ini, codebuild/release/prod-release.yml, codebuild/release/test-release.yml, requirements.txt, src/aws_encryption_sdk_cli/internal/identifiers.py
*Issue #, if available:* Mark 2.x End-of-Support 
- Update Changelog for release 2.1.2
- bump version for 2.1.2
- Pin AWS Encryption SDK for Python to at least version 2.5.1
- Add Support Policy
=> chore: 2.x End-of-Support 

tox.ini
*Issue #, if available:* Release 2.2.2
*Description of changes:* 
=> fix(tox): docs needs install but build must skip_install

README.rst
The readme incorrectly states that we support Python 3.6
=> fix: Update README.rst to specify Python support
